### ISSUE TITLE
Face segmentation with occlusions

### ISSUE THREAD

**Issue by wenbinTse** [isi-vista/structure_via_consensus#1]
Thanks for your paper and code. 
I notice that you use three-class segmentation in your origin paper, including face, background and occlusion, but in your code, the occlusion class has changed to hair. Can you share a demo of the former one? Besides, can you share the code to generate labels of faces with occlusions (**Factorizing out occlusions** in the paper)? Thanks a lot.

**Comment by iacopomasi** [comment]
Hi @wenbinTse ,
thanks for your interest in the paper. Yes, I have a network that returns a three-class mask (background, face, occlusion) for occlusion detection. I did not have the time to publish it yet with an inference script, though if you need it, I can try to just publish the weights so you can use it (the architecture is the same as the one of PartLabel so it should work immediately).

Regarding the factorization of occlusions, I thought about releasing the code but it sits too much on many libraries to prepare a clean notebook so I passed on that, but it should not be hard to reimplement. 

I hope this helps.

**Comment by TracelessLe** [comment]
Hello @iacopomasi, thanks for your great work. You reply to wenbinTse that you can share the weights of occlusion detection task, can you give a link for me to download it? 
Thanks a lot.

**Comment by iacopomasi** [comment]
@TracelessLe Thank you so much for your feedback. This is still in my TO-DO list but I did not find the time to upload the weights because I was busy on other projects. I may look at this in later August or September. I apologize and thank you again.

**Comment by TracelessLe** [comment]
> @TracelessLe Thank you so much for your feedback. This is still in my TO-DO list but I did not find the time to upload the weights because I was busy on other projects. I may look at this in later August or September. I apologize and thank you again.

Thanks, wait for it expectantly.

**Comment by rrryan2016** [comment]
Any update about this issue? :P

**Comment by iacopomasi** [comment]
Hi @rrryan2016 ,

I apologize but not yet. My list of priorities has been re-shuffled and I have been extremely busy lately so I am not sure when I will handle this now.

**Comment by tuandq-cs** [comment]
Hi @iacopomasi,
I am currently stuck with facial occlusions and found that your work may help my problem. I really need the weights of the occlusion detection task. Did you have any or some work like that? 
Thanks a lot.
