### ISSUE TITLE
Does the Consensus Loss work if the batch size is 1?

### ISSUE THREAD

**Issue by ygtxr1997** [isi-vista/structure_via_consensus#6]
What will happpen if the batch size is too small?

**Comment by iacopomasi** [comment]
I have not tested it with a batch equal to one but you can see yourself if the code does something wrong for this case. In theory, I should have vectorized the code to make it independent of the batch size, but there are always side cases.

**Comment by ygtxr1997** [comment]
Thank you! I misunderstood the equations in your paper. Now I think the code is independent of the batch size.
